import = ["/home/rodrigo/.config/alacritty/themes/themes/one_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

[colors.normal]
black =   '0x090618'
red =     '0xc34043'
green =   '0x76946a'
yellow =  '0xc0a36e'
blue =    '0x7e9cd8'
magenta = '0x957fb8'
cyan =    '0x6a9589'
white =   '0xc8c093'

[colors.bright]
black=   '0x727169'
red=     '0xe82424'
green =   '0x98bb6c'
yellow=  '0xe6c384'
blue=    '0x7fb4ca'
magenta= '0x938aa9'
cyan=    '0x7aa89f'
white =   '0xdcd7ba'

[colors.selection]
background = '0x2d4f67'
foreground = '0xc8c093'

