gui:
  theme:
    # Border color of focused window
    activeBorderColor:
      - "#7FB4CA" # Wave Blue

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#54546D" # Wave Gray

    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "#76946A" # Wave Green

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "#DCD7BA" # Wave Fg (Default Text)

    # Background color of selected line
    selectedLineBgColor:
      - "#223249" # Wave Selection Background

    # Background color of selected line when view doesn't have focus
    inactiveViewSelectedLineBgColor:
      - "#1F1F28" # Wave Dark Background

    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "#7FB4CA" # Wave Blue

    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "#1F1F28" # Wave Dark Background

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "#49443C" # Wave Pale Yellow

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "#2D4F67" # Wave Deep Blue

    # Color for file with unstaged changes
    unstagedChangesColor:
      - "#43242B" # Wave Red

    # Default text color
    defaultFgColor:
      - "#DCD7BA" # Wave Fg (Default Text)
