gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3

  theme:
    activeBorderColor:
      - "#7FB4CA"   # Wave Blue
      - bold

    inactiveBorderColor:
      - "#54546D"   # Wave Gray

    searchingActiveBorderColor:
      - "#2B3328"   # Wave Green
      - bold
  
    optionsTextColor:
      - "#DCD7BA"   # Wave Fg (Default Text)
      - bold

    selectedLineBgColor:
      - "#223249"   # Wave Selection Background

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#7FB4CA"   # Wave Blue

    cherryPickedCommitBgColor:
      - "#1F1F28"   # Wave Dark Background

    markedBaseCommitFgColor:
      - "#E6C384"   # Wave Pale Yellow

    markedBaseCommitBgColor:
      - "#2D4F67"   # Wave Deep Blue

    unstagedChangesColor:
      - "#43242B"   # Wave Red

    defaultFgColor:
      - "#DCD7BA"   # Wave Fg (Default Text)
