require("customizations.telescope-harpoon")
require("customizations.telescope-gitdiff")
require("customizations.hlsearch")
require("customizations.hover")
require("customizations.marks-float")
require("customizations.uuid-generator")
