return {
-- 	"cbochs/portal.nvim",
-- 	-- Optional dependencies
-- 	dependencies = {
-- 		"cbochs/grapple.nvim",
-- 		"ThePrimeagen/harpoon",
-- 	},
-- 	config = function()
-- 		require("portal").setup({
-- 			max_results = nil,
-- 			labels = { "h", "t", "n", "s" },
-- 			window_options = {
-- 				relative = "cursor",
-- 				width = 80,
-- 				height = 3,
-- 				col = 2,
-- 				focusable = false,
-- 				border = "single",
-- 				noautocmd = true,
-- 			},
-- 		})
--
-- 		-- vim.keymap.set(
-- 		-- 	"n",
-- 		-- 	"<leader>h",
-- 		-- 	require("portal.builtin").harpoon.tunnel,
-- 		-- 	{ nowait = true, desc = "[H]arpoon " }
-- 		-- )
-- 		vim.keymap.set("n", "<C-o>", "<cmd>Portal jumplist backward<cr>", { noremap = true })
-- 		vim.keymap.set("n", "<C-i>", "<cmd>Portal jumplist forward<cr>", { noremap = true })
-- 	end,
}
